### ISSUE TITLE
Use Prometheus instead of CloudWatch metrics

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#1733]
### Tasks

- [ ] Error resilience (batch and realtime) [0.75]
- [ ] Installation [0.5]
- [ ] Testing [1.25]

- [x] in-flight metrics (autoscaling) (Istio with mesh if easy, or NGINX or request monitor) [1.5]
- [x] Request metrics (status codes, latency) (Istio or NGINX or in Python) [0.75]
- [x] batch metrics [0.5]
- [x] `cortex get` metrics query (or link to Grafana dashboard) [0.5]

---

- [ ] Grafana installation [0.5]
- [ ] exposing Grafana (if/what to do about auth?) [0.5]
- [ ] Pod and node utilization metrics [0.25]

### Description

Use Prometheus instead of CloudWatch metrics for the following use cases:

* Autoscaling (it is worth revisiting if this can/should be collected from nginx or istio)
* Request / response code counts (it is worth revisiting where we collect these metrics, likely istio will be easiest, could also consider NGINX)
* Realtime API metrics (i.e. what is currently shown in the API dashboard)
* Batch API metrics

### Experiments to run
Install prometheus (look at statsd.yaml for tolerations) on a Cortex cluster and set up experiments to test the following scenarios:

* What is the smallest delay between when a metric is available to be scraped by prometheus to when it can be read from prometheus? (this delay will impact the autoscaling).
* Store batch metrics in prometheus. Prometheus works by pulling metrics. Batch API pods exit after they have completed, so there can be scenarios where Prometheus hasn't scraped all of the available Batch metrics before the pod exits.

### Related items

* Add a dashboard (global and/or per API, like we do now)
* Enable alerting
