### ISSUE TITLE
Support spot instances [2]

### ISSUE THREAD

**Issue by deliahu** [cortexlabs/cortex#469]
### Tasks

- [x] Expose the relevant spot instance configuration options in `eks.yaml` and prompt in CLI
- [x] Fetch max spot instance price
- [x] Autogenerate instance types similar to the target instance type
- [x] Suspend inter availability zone rebalancing: `aws autoscaling suspend-processes --auto-scaling-group-name <asg-name> --scaling-processes AZRebalance`
- [x] Inspect spot instance interrupt frequency

### Resources

* [eksctl docs](https://eksctl.io/usage/spot-instances/)
* [blog 1](https://alexei-led.github.io/post/eks_gpu_spot/): EKS GPU Cluster from Zero to Hero
* [blog 2](https://itnext.io/the-definitive-guide-to-running-ec2-spot-instances-as-kubernetes-worker-nodes-68ef2095e767): The definitive guide to running EC2 Spot Instances as Kubernetes worker nodes
* [GitHub CA thread](https://github.com/kubernetes/autoscaler/pull/1886)
* [AWS blog](https://aws.amazon.com/blogs/compute/introducing-the-capacity-optimized-allocation-strategy-for-amazon-ec2-spot-instances/)
* AWS [CloudFormation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-instancesdistribution.html), [EC2 docs](https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html)
* [Stack Overflow](https://stackoverflow.com/questions/55497202/how-to-limit-the-number-of-spot-instace-pools-in-an-asg)

### Motivation

Supporting spot instances (by default?) would make it cheaper to run APIs on Cortex
