### ISSUE TITLE
Separate operator and worker node group [2]

### ISSUE THREAD

**Issue by vishalbollu** [cortexlabs/cortex#500]
### Notes

* Side-effect: Enable worker node autoscaling to 0

### Tasks

- [x] Setup a dedicated nodegroup for workloads. Only schedule workloads on the workload nodegroup (including fluentd, nvidia and statsd).
- [ ] Operator calculates node capacity based on user specified instance type (saved in configmap)
- [ ] Update documentation to explain how min and max nodes will work.
- [ ] Update cluster autoscaler config and `versions.md` docs
- [x] Determine cortex node group instance type and count
