### ISSUE TITLE
Revisit `init()` in Predictor interface [0.5]

### ISSUE THREAD

**Issue by ospillinger** [cortexlabs/cortex#589]
### Description

Revisit automatic downloading, support non-S3 paths?

### Motivation

The `init()` API should be more intuitive.

### TODO
- [ ] remove model_key from predictor api
- [ ] enforce init function to return a model and update predict function to accept model
- [ ] update examples to follow new schema
